In [1]:
import pandas as pd
import numpy as np
import time
from matplotlib import pyplot as plt
import seaborn as sns
from countryinfo import CountryInfo

In [2]:
train = pd.read_csv("../data/train/train.csv")

In [3]:
train.head()

,Unnamed: 0,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,month,day
0,479,1916-07-02,Chile,Uruguay,0.0,4.0,COPA,Buenos Aires,Argentina,True,1916,7,2
1,481,1916-07-06,Argentina,Chile,6.0,1.0,COPA,Buenos Aires,Argentina,False,1916,7,6
2,482,1916-07-08,Brazil,Chile,1.0,1.0,COPA,Buenos Aires,Argentina,True,1916,7,8
3,483,1916-07-10,Argentina,Brazil,1.0,1.0,COPA,Buenos Aires,Argentina,False,1916,7,10
4,485,1916-07-12,Brazil,Uruguay,1.0,2.0,COPA,Buenos Aires,Argentina,True,1916,7,12

In [4]:
train.drop(columns=['Unnamed: 0'], inplace=True)

In [5]:
train['result'] = np.select(
    [
        train['home_score'] > train['away_score'],
        train['home_score'] < train['away_score']
    ],
    [
        1,  
        2   
    ],
    default=0 
)

In [6]:
train.drop(columns=['home_score', 'away_score'], inplace=True)

## FIFA Rankings

In [7]:
fifa = pd.read_csv('../data/raw/fifa_ranking.csv')
min_date = fifa['rank_date'].min()
train = train[train['date'] >= min_date]

In [19]:

all_teams = pd.concat([train['home_team'], train['away_team']]).unique()

missing_teams = [team for team in all_teams if team not in fifa['country_full'].values]

print(f"Total unique teams in train: {len(all_teams)}")
print(f"Teams NOT found in fifa['country_full']: {len(missing_teams)}")
print(missing_teams)

Total unique teams in train: 147
Teams NOT found in fifa['country_full']: 11
['United States', 'Ivory Coast', 'DR Congo', 'South Korea', 'Czech Republic', 'Iran', 'China', 'North Korea', 'Cape Verde', 'Kyrgyzstan', 'Gambia']

## Location

In [8]:
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

geolocator = Nominatim(
    user_agent="nations-matches-prediction",
    timeout=10
)

geocode = RateLimiter(
    geolocator.geocode,
    min_delay_seconds=2,   # Nominatim requests at most ~1/sec
    max_retries=2,
    error_wait_seconds=5,
    swallow_exceptions=False
)

In [9]:
def get_capital(country):
    try:
        return CountryInfo(country).capital()
    except:
        return None

In [10]:
def get_log_lat(city):
    try:
        location = geolocator.geocode(city)
        print(location.latitude, location.longitude)
        return location.latitude, location.longitude
    except Exception as e:
        raise e
        return None

In [11]:
train['home_capital'] = train['home_team'].apply(get_capital)
train['away_capital'] = train['away_team'].apply(get_capital)

In [12]:
train['home_comb'] = train['home_capital'] + ", " + train['home_team']
train['away_comb'] = train['away_capital'] + ", " + train['away_team']
train['stadium_comb'] = train['city'] + ", " + train['country']

In [13]:
train['home_comb']

1608             Quito, Ecuador
1609           Bogotá, Colombia
1610        Montevideo, Uruguay
1611    Buenos Aires, Argentina
1612           Brasília, Brazil
                 ...
4009            Zagreb, Croatia
4010              Madrid, Spain
4011        Ljubljana, Slovenia
4012        Copenhagen, Denmark
4013    Buenos Aires, Argentina
Name: home_comb, Length: 2406, dtype: str

In [14]:
train['stadium_comb']

1608            Quito, Ecuador
1609          Machala, Ecuador
1610           Ambato, Ecuador
1611        Guayaquil, Ecuador
1612           Cuenca, Ecuador
                 ...
4009          Hamburg, Germany
4010    Gelsenkirchen, Germany
4011           Munich, Germany
4012        Frankfurt, Germany
4013    Atlanta, United States
Name: stadium_comb, Length: 2406, dtype: str

In [15]:
import time
import json
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderRateLimited

geolocator = Nominatim(
    user_agent="nations-matches-prediction",
    timeout=10
)

CACHE_FILE = "coords_cache.json"

# Load existing cache so you never re-geocode the same place
try:
    with open(CACHE_FILE) as f:
        coords = json.load(f)
except (FileNotFoundError, json.JSONDecodeError):
    coords = {}

def get_coords(place):
    if place in coords:
        return coords[place]  # skip already-geocoded places
    
    for attempt in range(5):
        try:
            time.sleep(1.2)  # always wait before each request
            location = geolocator.geocode(place)
            result = (location.latitude, location.longitude) if location else None
            coords[place] = result

            # Save after every successful call
            with open(CACHE_FILE, "w") as f:
                json.dump(coords, f)

            return result

        except GeocoderRateLimited:
            wait = 60
            print(f"Rate limited on '{place}', waiting {wait}s (attempt {attempt+1}/5)")
            time.sleep(wait)

    print(f"Giving up on '{place}' after 5 attempts")
    coords[place] = None
    return None

places = pd.concat([
    train['home_comb'],
    train['away_comb'],
    train['stadium_comb']
]).dropna().unique()

for place in places:
    result = get_coords(place)
    print(f"{place}: {result}")

Quito, Ecuador: [-0.2201641, -78.5123274]
Bogotá, Colombia: [4.6533817, -74.0836331]
Montevideo, Uruguay: [-34.9058916, -56.1913095]
Buenos Aires, Argentina: [-34.6095579, -58.3887904]
Brasília, Brazil: [-15.7939869, -47.8828]
Asunción, Paraguay: [-25.2800459, -57.6343814]
Washington D.C., United States: [38.8950982, -77.0363849]
Mexico City, Mexico: [19.3207722, -99.1514678]
Santiago, Chile: [-33.4376995, -70.6510671]
Lima, Peru: [-12.0459808, -77.0305912]
Abuja, Nigeria: [9.0643305, 7.4892974]
Tunis, Tunisia: [36.8002068, 10.1857757]
Accra, Ghana: [5.5571096, -0.2012376]
Yamoussoukro, Ivory Coast: [6.8200066, -5.2776034]
Cairo, Egypt: [30.0443879, 31.2357257]
Bamako, Mali: [12.6132656, -7.9847391]
Dakar, Senegal: [14.693425, -17.447938]
Lusaka, Zambia: [-15.4163395, 28.2818414]
Kinshasa, DR Congo: [-4.3196982, 15.3424196]
Berlin, Germany: [52.5173885, 13.3951309]
Madrid, Spain: [40.416782, -3.703507]
Rome, Italy: [41.8933203, 12.4829321]
Brussels, Belgium: [50.8467372, 4.352493]
Yaoundé, Cameroon: [3.8689867, 11.5213344]
Oslo, Norway: [59.9133301, 10.7389701]
Amsterdam, Netherlands: [52.3730796, 4.8924534]
Bucharest, Romania: [44.4361414, 26.102684]
Seoul, South Korea: [37.5666791, 126.9782914]
Stockholm, Sweden: [59.3251172, 18.0710935]
Riyadh, Saudi Arabia: [24.638916, 46.7160104]
Sofia, Bulgaria: [42.6977028, 23.3217359]
Bern, Switzerland: [46.9484742, 7.4521749]
Sucre, Bolivia: [-19.0477251, -65.2594306]
Dublin, Republic of Ireland: [53.3493795, -6.2605593]
Moscow, Russia: [55.625578, 37.6063916]
Rabat, Morocco: [34.0218454, -6.8408929]
Athens, Greece: [37.9755648, 23.7348324]
Pretoria, South Africa: [-25.7459277, 28.1879101]
Freetown, Sierra Leone: [8.479004, -13.26795]
Libreville, Gabon: [0.4086518, 9.4418849]
Algiers, Algeria: [36.7729333, 3.0588445]
Ouagadougou, Burkina Faso: [12.3681873, -1.5270944]
Maputo, Mozambique: [-25.966213, 32.56745]
Luanda, Angola: [-8.8272699, 13.2439512]
Monrovia, Liberia: [6.3203562, -10.8060492]
Copenhagen, Denmark: [55.6867243, 12.5700724]
Ankara, Turkey: [39.9207759, 32.8540497]
Prague, Czech Republic: [50.0874654, 14.4212535]
Lisbon, Portugal: [38.7077507, -9.1365919]
Paris, France: [48.8534951, 2.3483915]
Zagreb, Croatia: [45.8130967, 15.9772795]
Edinburgh, Scotland: [55.9533456, -3.1883749]
Jakarta, Indonesia: [-6.1754049, 106.827168]
Abu Dhabi, United Arab Emirates: [24.4538352, 54.3774014]
Tehran, Iran: [35.6892523, 51.3896004]
Beijing, China: [39.9057136, 116.3912972]
Tokyo, Japan: [35.6768601, 139.7638947]
Bangkok, Thailand: [13.7524938, 100.4935089]
Damascus, Syria: [33.5130695, 36.3095814]
Kuwait City, Kuwait: [29.3796532, 47.9734174]
Baghdad, Iraq: [33.3061701, 44.3872213]
Tashkent, Uzbekistan: [41.3123363, 69.2787079]
Kingston, Jamaica: [17.9712148, -76.7928128]
Belgrade, Serbia: [44.8153318, 20.4456588]
Ljubljana, Slovenia: [46.0500268, 14.5069289]
Beirut, Lebanon: [33.8892265, 35.5025585]
Doha, Qatar: [25.3108807, 51.5081812]
Tegucigalpa, Honduras: [14.1058135, -87.2047053]
Lomé, Togo: [6.130419, 1.215829]
San José, Costa Rica: [9.9327707, -84.0796144]
Warsaw, Poland: [52.2319581, 21.0067249]
Harare, Zimbabwe: [-17.8567035, 31.0601584]
Nairobi, Kenya: [-1.2890006, 36.8172812]
Kigali, Rwanda: [-1.9534357, 30.1140089]
Riga, Latvia: [56.9493977, 24.1051846]
Caracas, Venezuela: [10.5060934, -66.9146008]
Manama, Bahrain: [26.2235041, 50.5822436]
Ashgabat, Turkmenistan: [37.9404648, 58.3823487]
Amman, Jordan: [31.9515694, 35.9239625]
Muscat, Oman: [23.6123628, 58.5938134]
Tripoli, Libya: [32.896672, 13.1777923]
Conakry, Guinea: [9.5170602, -13.6998434]
Port of Spain, Trinidad and Tobago: [10.6572678, -61.5180173]
Canberra, Australia: [-35.2975906, 149.1012676]
Kyiv, Ukraine: [50.4500336, 30.5241361]
Hanoi, Vietnam: [21.0283334, 105.854041]
Kuala Lumpur, Malaysia: [3.1516964, 101.6942371]
Windhoek, Namibia: [-22.5776104, 17.0772739]
Khartoum, Sudan: [15.5635972, 32.5349123]
Vienna, Austria: [48.2083537, 16.3725042]
Lilongwe, Malawi: [-13.9875107, 33.768144]
Wellington, New Zealand: [-41.2887953, 174.7772114]
Bratislava, Slovakia: [48.1516988, 17.1093063]
Pyongyang, North Korea: [39.0167979, 125.7473609]
New Delhi, India: [28.6138954, 77.2090057]
Malabo, Equatorial Guinea: [3.741877, 8.7740663]
Niamey, Niger: [13.524834, 2.109823]
Gaborone, Botswana: [-24.6581357, 25.9088474]
Praia, Cape Verde: [14.9162811, -23.5095095]
Addis Ababa, Ethiopia: [9.0358119, 38.7524315]
Sarajevo, Bosnia and Herzegovina: [43.8570713, 18.4126147]
Ramallah, Palestine: [31.9158969, 35.1781625]
Brazzaville, Congo: [-4.2694407, 15.2712256]
Port-au-Prince, Haiti: [18.547327, -72.3395928]
Panama City, Panama: [8.9714493, -79.5341802]
Tirana, Albania: [41.3281482, 19.8184435]
Reykjavik, Iceland: [64.145981, -21.9422367]
Budapest, Hungary: [47.4813896, 19.1457723]
Bissau, Guinea-Bissau: [11.861324, -15.583055]
Kampala, Uganda: [0.3177137, 32.5813539]
Nur-Sultan, Kazakhstan: [51.1282205, 71.4306682]
Yerevan, Armenia: [40.1777112, 44.5126233]
Gibraltar, Gibraltar: [36.140807, -5.3541295]
Vilnius, Lithuania: [54.6870458, 25.2829111]
Tórshavn, Faroe Islands: [62.0101396, -6.7715709]
Baku, Azerbaijan: [40.3755885, 49.8328009]
Helsinki, Finland: [60.1666204, 24.9435408]
Tallinn, Estonia: [59.437242, 24.7572693]
Minsk, Belarus: [53.9024716, 27.5618225]
Luxembourg, Luxembourg: [49.6112768, 6.129799]
Nicosia, Cyprus: [35.1746503, 33.3638783]
Tbilisi, Georgia: [41.6934591, 44.8014495]
Skopje, North Macedonia: [41.9962164, 21.4318935]
Vaduz, Liechtenstein: [47.1392862, 9.5227962]
Podgorica, Montenegro: [42.4415238, 19.2621081]
Andorra la Vella, Andorra: [42.4979185, 1.5032264]
Valletta, Malta: [35.8989979, 14.5136607]
City of San Marino, San Marino: [43.9363996, 12.4466991]
Chișinău, Moldova: [47.0245117, 28.8322923]
Jerusalem, Israel: [31.7788472, 35.2257856]
Manila, Philippines: [14.5904492, 120.9803621]
Bishkek, Kyrgyzstan: [42.8761424, 74.6036724]
Sana'a, Yemen: [15.35, 44.2]
Antananarivo, Madagascar: [-18.9100122, 47.5255809]
Nouakchott, Mauritania: [18.0792379, -15.9780071]
Porto-Novo, Benin: [6.4990718, 2.6253361]
Bujumbura, Burundi: [-3.3638125, 29.3675028]
Dodoma, Tanzania: [-6.1791181, 35.7468174]
Moroni, Comoros: [-11.7040306, 43.251909]
Banjul, Gambia: [13.4410165, -16.5627509]
Ottawa, Canada: [45.4208777, -75.6901106]
City of Victoria, Hong Kong: [22.2765855, 114.1693011]
Dushanbe, Tajikistan: [38.5767045, 68.785433]
Machala, Ecuador: [-3.3148937, -79.9512804]
Ambato, Ecuador: [-1.2422413, -78.6287594]
Guayaquil, Ecuador: [-2.1900572, -79.8868669]
Cuenca, Ecuador: [-2.8974072, -79.0041726]
Portoviejo, Ecuador: [-1.05282, -80.4534134]
Sousse, Tunisia: [35.8288284, 10.6405254]
Chicago, United States: [41.8755616, -87.6244212]
Dallas, United States: [32.7762719, -96.7968559]
Pasadena, United States: [34.1476507, -118.144155]
East Rutherford, United States: [40.833989, -74.0970865]
Pontiac, United States: [42.6389216, -83.2910468]
Orlando, United States: [28.5421218, -81.379045]
Washington, D.C., United States: [38.8950982, -77.0363849]
Palo Alto, United States: [37.4443293, -122.1598465]
Foxborough, United States: [42.0653768, -71.2478308]
Maldonado, Uruguay: [-34.9087162, -54.9582718]
Rivera, Uruguay: [-30.900058, -55.5408151]
Paysandú, Uruguay: [-32.3217257, -58.0892136]
Johannesburg, South Africa: [-26.205, 28.049722]
Port Elizabeth, South Africa: [-33.9618598, 25.6186731]
Bloemfontein, South Africa: [-29.116395, 26.215496]
Durban, South Africa: [-29.861825, 31.009909]
London, England: [51.5074456, -0.1277653]
Sheffield, England: [53.3806626, -1.4702278]
Manchester, England: [53.4424618, -2.2324547]
Leeds, England: [53.7974185, -1.5437941]
Birmingham, England: [52.4948994, -1.8518439]
Newcastle, England: [54.9738474, -1.6131572]
Liverpool, England: [53.3933411, -2.9166389]
Nottingham, England: [52.9534193, -1.1496461]
Dubai, United Arab Emirates: [25.0742823, 55.1885387]
Al Ain, United Arab Emirates: [24.2248697, 55.7452211]
Cochabamba, Bolivia: [-17.4012458, -66.1675681]
La Paz, Bolivia: [-16.4955455, -68.1336229]
Santa Cruz, Bolivia: [-17.7834217, -63.1820853]
Oruro, Bolivia: [-18.666667, -67.666667]
Bobo Dioulasso, Burkina Faso: [11.1765796, -4.2961436]
Saint-Denis, France: [48.9383732, 2.3627508]
Montpellier, France: [43.6112422, 3.8767337]
Toulouse, France: [43.6044638, 1.4442433]
Bordeaux, France: [44.841225, -0.5800364]
Marseille, France: [43.2963986, 5.3777888]
Lens, France: [50.4291723, 2.8319805]
Lyon, France: [45.7578137, 4.8320114]
Nantes, France: [47.2186371, -1.5541362]
Saint-Étienne, France: [45.4401467, 4.3873058]
Ciudad del Este, Paraguay: [-25.5169015, -54.6168645]
Luque, Paraguay: [-25.2665417, -57.4926928]
Pedro Juan Caballero, Paraguay: [-22.5497781, -55.7384312]
Kano, Nigeria: [11.9939978, 8.5219738]
Lagos, Nigeria: [6.4550575, 3.3941795]
Kumasi, Ghana: [6.6985605, -1.6233086]
Bruges, Belgium: [51.2085526, 3.226772]
Arnhem, Netherlands: [52.0056642, 5.8762345]
Liège, Belgium: [50.6450944, 5.5736112]
Eindhoven, Netherlands: [51.4392648, 5.478633]
Charleroi, Belgium: [50.4116233, 4.444528]
Rotterdam, Netherlands: [51.9244424, 4.47775]
Tripoli, Lebanon: [34.4373616, 35.8348551]
Sidon, Lebanon: [33.564733, 35.374978]
Barranquilla, Colombia: [11.0101922, -74.8231794]
Cali, Colombia: [3.4108435, -76.5812127]
Medellín, Colombia: [6.2697324, -75.6025597]
Pereira, Colombia: [4.7854606, -75.788322]
Armenia, Colombia: [4.4919894, -75.7413961]
Manizales, Colombia: [5.0743694, -75.5081167]
Sikasso, Mali: [11.529684, -6.8663259]
Ségou, Mali: [13.441518, -6.268147]
Mopti, Mali: [14.514489, -3.6464581]
Kayes, Mali: [13.8001844, -10.2245548]
Sapporo, Japan: [43.061936, 141.3542924]
Niigata, Japan: [37.6452283, 138.7669125]
Ulsan, South Korea: [35.5391697, 129.3119136]
Kashima, Japan: [35.9661164, 140.6450292]
Saitama, Japan: [35.9754168, 139.4160114]
Busan, South Korea: [35.1799528, 129.0752365]
Gwangju, South Korea: [35.1558147, 126.8306362]
Kobe, Japan: [34.6932379, 135.1943764]
Suwon, South Korea: [37.2633325, 127.0287472]
Daegu, South Korea: [35.8713, 128.6018]
Jeonju, South Korea: [35.8237631, 127.1472805]
Seogwipo, South Korea: [33.252845, 126.5610278]
Incheon, South Korea: [37.456, 126.7052]
Yokohama, Japan: [35.4503381, 139.6343802]
Rifu, Japan: [38.3301406, 140.9753442]
Ōita, Japan: [33.1819875, 131.4270217]
Fukuroi, Japan: [34.7501492, 137.9246962]
Osaka, Japan: [34.6937569, 135.5014539]
Daejeon, South Korea: [36.3497007, 127.3849016]
Radès, Tunisia: [36.767891, 10.2724617]
Sfax, Tunisia: [34.7394361, 10.7604024]
Bizerte, Tunisia: [37.2720905, 9.8708565]
Monastir, Tunisia: [35.7707582, 10.8280511]
Porto, Portugal: [41.1502195, -8.6103497]
Faro, Portugal: [37.0162944, -7.935182]
Leiria, Portugal: [39.7437902, -8.8071119]
Guimarães, Portugal: [41.4417677, -8.2955712]
Aveiro, Portugal: [40.640496, -8.6537841]
Coimbra, Portugal: [40.2111931, -8.4294632]
Braga, Portugal: [41.5510583, -8.4280045]
Chiclayo, Peru: [-6.7716146, -79.8387175]
Arequipa, Peru: [-16.3988667, -71.5369607]
Trujillo, Peru: [-8.1116778, -79.0287742]
Piura, Peru: [-5.0, -80.333333]
Tacna, Peru: [-18.01386, -70.2511032]
Chengdu, China: [30.659867, 104.063315]
Jinan, China: [36.6519754, 117.1138479]
Chongqing, China: [30.05518, 107.8748712]
Cusco, Peru: [-13.5170887, -71.9785356]
Alexandria, Egypt: [31.1991806, 29.8951716]
Port Said, Egypt: [31.263235, 32.305505]
Ismailia, Egypt: [30.6043775, 32.2770825]
Munich, Germany: [48.1371079, 11.5753822]
Gelsenkirchen, Germany: [51.5110321, 7.0960124]
Hamburg, Germany: [53.5501721, 10.0013165]
Frankfurt, Germany: [50.1106444, 8.6820917]
Dortmund, Germany: [51.5142273, 7.4652789]
Cologne, Germany: [50.938361, 6.959974]
Nuremberg, Germany: [49.453872, 11.077298]
Leipzig, Germany: [51.3406321, 12.3747329]
Kaiserslautern, Germany: [49.4432174, 7.7689951]
Hanover, Germany: [52.3744779, 9.7385532]
Stuttgart, Germany: [48.7784485, 9.1800132]
Mérida, Venezuela: [8.5816963, -71.1658075]
San Cristóbal, Venezuela: [7.7756663, -72.2214154]
Puerto Ordaz, Venezuela: [8.2750351, -62.7558263]
Maracaibo, Venezuela: [10.6498095, -71.6443596]
Barinas, Venezuela: [8.1450535, -69.8567392]
Maturín, Venezuela: [9.7422774, -63.1888854]
Puerto la Cruz, Venezuela: [10.2028617, -64.6307626]
Barquisimeto, Venezuela: [10.0774374, -69.3222293]
Ho Chi Minh City, Vietnam: [10.7737261, 106.7166008]
Palembang, Indonesia: [-2.9888243, 104.7568507]
Shah Alam, Malaysia: [3.0739429, 101.5185278]
Sekondi, Ghana: [4.927456, -1.7490216]
Tamale, Ghana: [9.4051992, -0.8423986]
Geneva, Switzerland: [46.2017559, 6.1466014]
Basel, Switzerland: [47.5581077, 7.5878261]
Klagenfurt, Austria: [46.623943, 14.3075976]
Zürich, Switzerland: [47.3744489, 8.5410422]
Salzburg, Austria: [47.7981346, 13.0464806]
Innsbruck, Austria: [47.2654296, 11.3927685]
Cabinda, Angola: [-5.056395, 12.3211749]
Benguela, Angola: [-12.5790048, 13.4037117]
Lubango, Angola: [-14.9195617, 13.4897509]
Cape Town, South Africa: [-33.9288301, 18.4172197]
Rustenburg, South Africa: [-25.665655, 27.241448]
Polokwane, South Africa: [-23.9058333, 29.4613889]
Nelspruit, South Africa: [-25.4729094, 30.9772719]
Al Rayyan, Qatar: [25.0819602, 51.158416]
La Plata, Argentina: [-34.9206797, -57.9537638]
San Salvador de Jujuy, Argentina: [-24.1852569, -65.2994789]
Santa Fe, Argentina: [-30.3154739, -61.1645076]
San Juan, Argentina: [-30.7054363, -69.1988222]
Mendoza, Argentina: [-34.5970325, -68.7304797]
Córdoba, Argentina: [-31.4166867, -64.1834193]
Salta, Argentina: [-25.2269908, -64.5911956]
Bata, Equatorial Guinea: [2.0064092, 9.9087683]
Franceville, Gabon: [-1.6343979, 13.5894808]
Wrocław, Poland: [51.1089776, 17.0326689]
Lviv, Ukraine: [49.841952, 24.0315921]
Kharkiv, Ukraine: [49.9923181, 36.2310146]
Poznań, Poland: [52.4006632, 16.9197326]
Gdańsk, Poland: [54.4288032, 18.798327]
Donetsk, Ukraine: [47.9212914, 37.7809825]
São Paulo, Brazil: [-23.5506507, -46.6333824]
Cuiabá, Brazil: [-15.5986686, -56.0991301]
Natal, Brazil: [-5.805398, -35.2080905]
Salvador, Brazil: [-12.9822499, -38.4812772]
Belo Horizonte, Brazil: [-19.9227318, -43.9450948]
Manaus, Brazil: [-3.1316333, -59.9825041]
Recife, Brazil: [-8.0584933, -34.8848193]
Fortaleza, Brazil: [-3.7932167, -38.5280359]
Rio de Janeiro, Brazil: [-22.9110137, -43.2093727]
Porto Alegre, Brazil: [-30.0324999, -51.2303767]
Curitiba, Brazil: [-25.4295963, -49.2712724]
Melbourne, Australia: [-37.8142454, 144.9631732]
Brisbane, Australia: [-27.4689623, 153.0235009]
Sydney, Australia: [-33.8698439, 151.2082848]
Newcastle, Australia: [-32.9192953, 151.7795348]
Ebebiyín, Equatorial Guinea: [2.1537363, 11.3370815]
Mongomo, Equatorial Guinea: [1.6282551, 11.3184671]
Viña del Mar, Chile: [-33.0244535, -71.5517636]
La Serena, Chile: [-29.902705, -71.2519575]
Antofagasta, Chile: [-23.6463741, -70.3980033]
Temuco, Chile: [-38.7358908, -72.590538]
Rancagua, Chile: [-34.1702433, -70.740718]
Valparaíso, Chile: [-33.0458456, -71.6196749]
Concepción, Chile: [-36.8270698, -73.0502064]
Santa Clara, United States: [37.2333253, -121.6846349]
Seattle, United States: [47.6038321, -122.330062]
Glendale, United States: [34.1469416, -118.2478471]
Philadelphia, United States: [39.9527237, -75.1635262]
Houston, United States: [29.7589382, -95.3676974]
Villeneuve-d'Ascq, France: [50.6193174, 3.1314002]
Nice, France: [43.7009358, 7.2683912]
Oyem, Gabon: [1.5997904, 11.5751003]
Port-Gentil, Gabon: [-0.7151966, 8.7787919]
Ekaterinburg, Russia: [56.8382071, 60.6007886]
Saint Petersburg, Russia: [59.9606739, 30.1586551]
Sochi, Russia: [43.5854823, 39.723109]
Kazan, Russia: [55.7946485, 49.1115022]
Saransk, Russia: [54.18671, 45.18383]
Kaliningrad, Russia: [54.710128, 20.5105838]
Samara, Russia: [53.1956255, 50.1014927]
Rostov-on-Don, Russia: [47.2610441, 39.7249086]
Nizhny Novgorod, Russia: [56.3264816, 44.0051395]
Volgograd, Russia: [48.7081906, 44.5153353]
Uherské Hradiště, Czech Republic: [49.0681018, 17.4663899]
Cardiff, Wales: [51.4816546, -3.1791934]
Astana, Kazakhstan: [51.1282205, 71.4306682]
Bologna, Italy: [44.4938203, 11.3426327]
Trabzon, Turkey: [41.0054605, 39.7301463]
Elbasan, Albania: [41.1126792, 20.0820858]
Ploiești, Romania: [44.9417468, 26.0236504]
St. Gallen, Switzerland: [47.425618, 9.3762397]
Belfast, Northern Ireland: [54.596391, -5.9301829]
Tampere, Finland: [61.4977988, 23.7616335]
Aarhus, Denmark: [56.1496278, 10.2134046]
Glasgow, Scotland: [55.861155, -4.2501687]
Pristina, Kosovo: [42.6638771, 21.1640849]
Attard, Malta: [35.8909172, 14.4430093]
Reykjavík, Iceland: [64.145981, -21.9422367]
Elche, Spain: [38.2653307, -0.6988391]
Zenica, Bosnia and Herzegovina: [44.199828, 17.9093012]
Turku, Finland: [60.4515932, 22.2669991]
Serravalle, San Marino: [43.9699026, 12.4802946]
Chorzów, Poland: [50.2884726, 18.9703798]
Haifa, Israel: [32.8191218, 34.9983856]
Rijeka, Croatia: [45.3267976, 14.442208]
Trnava, Slovakia: [48.374218, 17.5809299]
Beer Sheva, Israel: [31.2457442, 34.7925181]
Seville, Spain: [37.3886303, -5.9953403]
Milan, Italy: [45.4641943, 9.1896346]
Konya, Turkey: [37.872734, 32.4924376]
Shkodër, Albania: [42.0681371, 19.5121437]
Lucerne, Switzerland: [47.052144, 8.3058123]
Sharjah, United Arab Emirates: [24.9760668, 56.2536044]
Suez, Egypt: [29.974498, 32.537086]
Sivas, Turkey: [39.4191717, 37.1012388]
Parma, Italy: [44.6952006, 10.0979869]
Florence, Italy: [43.7697955, 11.2556404]
Olomouc, Czech Republic: [49.5940567, 17.251143]
Netanya, Israel: [32.3286181, 34.8566246]
Almaty, Kazakhstan: [43.2363924, 76.9457275]
Rimini, Italy: [43.9465433, 12.630749]
Tychy, Poland: [50.114397, 18.9965933]
Bergamo, Italy: [45.7566557, 9.7542192]
Istanbul, Turkey: [41.006381, 28.9758715]
Zaprešić, Croatia: [45.8572728, 15.8050436]
Ta' Qali, Malta: [35.8923492, 14.4196785]
Reggio Emilia, Italy: [44.6086674, 10.5940667]
Leuven, Belgium: [50.879202, 4.7011675]
Plzeň, Czech Republic: [49.7477415, 13.3775249]
Split, Croatia: [43.5116383, 16.4399659]
Goiânia, Brazil: [-16.680882, -49.2532691]
Turin, Italy: [45.0677551, 7.6824892]
Bafoussam, Cameroon: [5.4758844, 10.4217852]
Garoua, Cameroon: [9.3070698, 13.3934527]
Douala, Cameroon: [4.0429389, 9.7062018]
Limbé, Cameroon: [4.010289, 9.207058]
Larnaca, Cyprus: [34.9236095, 33.6236184]
Razgrad, Bulgaria: [43.6394793, 26.7022408]
Osijek, Croatia: [45.5548793, 18.6953685]
Novi Sad, Serbia: [45.2551338, 19.8451756]
Cesena, Italy: [44.136352, 12.2422442]
Vólos, Greece: [39.3624833, 22.9401864]
Mardakan, Azerbaijan: [40.4935881, 50.1495477]
Wolverhampton, England: [52.5847651, -2.127567]
Łódź, Poland: [51.7728245, 19.478486]
Málaga, Spain: [36.7647913, -4.4422005]
Mönchengladbach, Germany: [51.1947131, 6.4353792]
İzmir, Turkey: [38.4192537, 27.128469]
Zaragoza, Spain: [41.6915847, -0.9101268]
Tel Aviv, Israel: [32.0852997, 34.7818064]
Bačka Topola, Serbia: [45.8121657, 19.6304705]
Kraków, Poland: [50.0469432, 19.9971534]
Al Khor, Qatar: [25.7567822, 51.3269839]
Lusail, Qatar: [25.4228888, 51.5197163]
Al Wakrah, Qatar: [25.0037453, 51.4103338]
Enschede, Netherlands: [52.2209855, 6.8940537]
Ebimpé, Ivory Coast: [5.4995714, -4.0800574]
Abidjan, Ivory Coast: [5.320357, -4.016107]
Bouaké, Ivory Coast: [7.6890212, -5.0283552]
Korhogo, Ivory Coast: [9.4580698, -5.6316293]
San-Pédro, Ivory Coast: [4.7589989, -6.6463922]
Faro-Loulé, Portugal: [37.0891428, -8.1168249]
Kaunas, Lithuania: [54.8982139, 23.9044817]
Düsseldorf, Germany: [51.2254018, 6.7763137]
Atlanta, United States: [33.7544657, -84.3898151]

In [16]:
train[['home_lat', 'home_lon']] = (
    train['home_comb']
    .map(coords)
    .apply(pd.Series)
)

train[['away_lat', 'away_lon']] = (
    train['away_comb']
    .map(coords)
    .apply(pd.Series)
)

train[['stadium_lat', 'stadium_lon']] = (
    train['stadium_comb']
    .map(coords)
    .apply(pd.Series)
)

In [17]:
train.head()

,date,home_team,away_team,tournament,city,country,neutral,year,month,day,...,away_capital,home_comb,away_comb,stadium_comb,home_lat,home_lon,away_lat,away_lon,stadium_lat,stadium_lon
1608,1993-06-15,Ecuador,Venezuela,COPA,Quito,Ecuador,False,1993,6,15,...,Caracas,"Quito, Ecuador","Caracas, Venezuela","Quito, Ecuador",-0.220164,-78.512327,10.506093,-66.914601,-0.220164,-78.512327
1609,1993-06-16,Colombia,Mexico,COPA,Machala,Ecuador,True,1993,6,16,...,Mexico City,"Bogotá, Colombia","Mexico City, Mexico","Machala, Ecuador",4.653382,-74.083633,19.320772,-99.151468,-3.314894,-79.951280
1610,1993-06-16,Uruguay,United States,COPA,Ambato,Ecuador,True,1993,6,16,...,Washington D.C.,"Montevideo, Uruguay","Washington D.C., United States","Ambato, Ecuador",-34.905892,-56.191310,38.895098,-77.036385,-1.242241,-78.628759
1611,1993-06-17,Argentina,Bolivia,COPA,Guayaquil,Ecuador,True,1993,6,17,...,Sucre,"Buenos Aires, Argentina","Sucre, Bolivia","Guayaquil, Ecuador",-34.609558,-58.388790,-19.047725,-65.259431,-2.190057,-79.886867
1612,1993-06-18,Brazil,Peru,COPA,Cuenca,Ecuador,True,1993,6,18,...,Lima,"Brasília, Brazil","Lima, Peru","Cuenca, Ecuador",-15.793987,-47.882800,-12.045981,-77.030591,-2.897407,-79.004173

## Weather

In [18]:
import requests

def get_weather_url(lat, lon, date):
        
    try:
        history = requests.get(
            "https://archive-api.open-meteo.com/v1/archive",
            params={
                    "latitude": lat,
                    "longitude": lon,
                    "start_date": date,
                    "end_date": date,
                    "daily": "temperature_2m_max,temperature_2m_min,precipitation_sum,wind_speed_10m_max",
                    "timezone": "auto"
                }
            ).json()
        return {
            'temperature_max' : history['daily']['temperature_2m_max'][0],
            'temperature_min' : history['daily']['temperature_2m_min'][0],
            'precipitation' : history['daily']['precipitation_sum'][0],
            'wind_speed' : history['daily']['wind_speed_10m_max'][0]
        }
    except:
        raise Exception("Error")

In [ ]:
import json

CACHE_FILE = "weather_cache.json"

# Load cache
try:
    with open(CACHE_FILE) as f:
        weather = json.load(f)
except FileNotFoundError:
    weather = {}

def cache_key(lat, lon, date):
    return f"{lat}_{lon}_{date}"  

def get_weather(lat, lon, date):
    key = cache_key(lat, lon, date)

    if key in weather:
        print(f"Cache hit for {key}")
        return weather[key]  

    for attempt in range(5):
        try:
            time.sleep(1.2)  # respect 600/min limit (~1 req/sec)
            result = get_weather_url(lat, lon, date)

            weather[key] = result
            print("result is back for ", (lon, lat, date))
            with open(CACHE_FILE, "w") as f:
                json.dump(weather, f)

            return result

        except Exception as e:
            wait = 60
            print(f"Error: {e}, waiting {wait}s (attempt {attempt+1}/5)")
            time.sleep(wait)

    print(f"Giving up on ({lat}, {lon}, {date}) after 5 attempts")
    weather[key] = None
    return None

In [20]:
train.dropna(inplace=True)

In [ ]:

unique = train[['home_lat', 'home_lon', 'date']].drop_duplicates()

unique['weather'] = unique.apply(
    lambda row: get_weather(row['home_lat'], row['home_lon'], row['date']),
    axis=1
)

weather_df = unique['weather'].apply(pd.Series)
unique = pd.concat([unique, weather_df], axis=1).drop(columns='weather')

train = train.merge(unique, on=['home_lat', 'home_lon', 'date'], how='left')

Cache hit for -0.2201641_-78.5123274_1993-06-15
Cache hit for 4.6533817_-74.0836331_1993-06-16
Cache hit for -34.9058916_-56.1913095_1993-06-16
Cache hit for -34.6095579_-58.3887904_1993-06-17
Cache hit for -15.7939869_-47.8828_1993-06-18
Cache hit for -25.2800459_-57.6343814_1993-06-18
Cache hit for -0.2201641_-78.5123274_1993-06-19
Cache hit for -34.9058916_-56.1913095_1993-06-19
Cache hit for -34.6095579_-58.3887904_1993-06-20
Cache hit for 4.6533817_-74.0836331_1993-06-20
Cache hit for -15.7939869_-47.8828_1993-06-21
Cache hit for -25.2800459_-57.6343814_1993-06-21
Cache hit for -0.2201641_-78.5123274_1993-06-22
Cache hit for 38.8950982_-77.0363849_1993-06-22
Cache hit for -34.6095579_-58.3887904_1993-06-23
Cache hit for 19.3207722_-99.1514678_1993-06-23
Cache hit for -15.7939869_-47.8828_1993-06-24
Cache hit for -33.4376995_-70.6510671_1993-06-24
Cache hit for 4.6533817_-74.0836331_1993-06-26
Cache hit for -0.2201641_-78.5123274_1993-06-26
Cache hit for -15.7939869_-47.8828_1993-06-27
Cache hit for -12.0459808_-77.0305912_1993-06-27
Cache hit for -0.2201641_-78.5123274_1993-06-30
Cache hit for 4.6533817_-74.0836331_1993-07-01
Cache hit for -0.2201641_-78.5123274_1993-07-03
Cache hit for -34.6095579_-58.3887904_1993-07-04
Cache hit for 9.0643305_7.4892974_1994-03-26
Cache hit for 36.8002068_10.1857757_1994-03-26
Cache hit for 5.5571096_-0.2012376_1994-03-27
Cache hit for 6.8200066_-5.2776034_1994-03-27
Cache hit for 30.0443879_31.2357257_1994-03-28
Cache hit for 12.6132656_-7.9847391_1994-03-28
Cache hit for 14.693425_-17.447938_1994-03-29
Cache hit for -15.4163395_28.2818414_1994-03-29
Cache hit for 9.0643305_7.4892974_1994-03-30
Cache hit for 36.8002068_10.1857757_1994-03-30
Cache hit for 5.5571096_-0.2012376_1994-03-31
Cache hit for -15.4163395_28.2818414_1994-03-31
Cache hit for -4.3196982_15.3424196_1994-04-02
Cache hit for 30.0443879_31.2357257_1994-04-02
Cache hit for 5.5571096_-0.2012376_1994-04-03
Cache hit for -15.4163395_28.2818414_1994-04-03
Cache hit for 9.0643305_7.4892974_1994-04-06
Cache hit for -15.4163395_28.2818414_1994-04-06
Cache hit for 6.8200066_-5.2776034_1994-04-10
Cache hit for 9.0643305_7.4892974_1994-04-10
Cache hit for 52.5173885_13.3951309_1994-06-17
Cache hit for 40.416782_-3.703507_1994-06-17
Cache hit for 4.6533817_-74.0836331_1994-06-18
Cache hit for 41.8933203_12.4829321_1994-06-18
Cache hit for 38.8950982_-77.0363849_1994-06-18
Cache hit for 50.8467372_4.352493_1994-06-19
Cache hit for 3.8689867_11.5213344_1994-06-19
Cache hit for 59.9133301_10.7389701_1994-06-19
Cache hit for -15.7939869_-47.8828_1994-06-20
Cache hit for 52.3730796_4.8924534_1994-06-20
Cache hit for -34.6095579_-58.3887904_1994-06-21
Cache hit for 52.5173885_13.3951309_1994-06-21
Cache hit for 9.0643305_7.4892974_1994-06-21
Cache hit for 44.4361414_26.102684_1994-06-22
Cache hit for 38.8950982_-77.0363849_1994-06-22
Cache hit for 41.8933203_12.4829321_1994-06-23
Cache hit for 37.5666791_126.9782914_1994-06-23
Cache hit for -15.7939869_-47.8828_1994-06-24
Cache hit for 19.3207722_-99.1514678_1994-06-24
Cache hit for 59.3251172_18.0710935_1994-06-24
Cache hit for -34.6095579_-58.3887904_1994-06-25
Cache hit for 50.8467372_4.352493_1994-06-25
Cache hit for 24.638916_46.7160104_1994-06-25
Cache hit for 42.6977028_23.3217359_1994-06-26
Cache hit for 46.9484742_7.4521749_1994-06-26
Cache hit for 38.8950982_-77.0363849_1994-06-26
Cache hit for -19.0477251_-65.2594306_1994-06-27
Cache hit for 52.5173885_13.3951309_1994-06-27
Cache hit for -15.7939869_-47.8828_1994-06-28
Cache hit for 53.3493795_-6.2605593_1994-06-28
Cache hit for 41.8933203_12.4829321_1994-06-28
Cache hit for 55.625578_37.6063916_1994-06-28
Cache hit for 50.8467372_4.352493_1994-06-29
Cache hit for 34.0218454_-6.8408929_1994-06-29
Cache hit for -34.6095579_-58.3887904_1994-06-30
Cache hit for 37.9755648_23.7348324_1994-06-30
Cache hit for 52.5173885_13.3951309_1994-07-02
Cache hit for 40.416782_-3.703507_1994-07-02
Cache hit for 44.4361414_26.102684_1994-07-03
Cache hit for 24.638916_46.7160104_1994-07-03
Cache hit for 52.3730796_4.8924534_1994-07-04
Cache hit for 38.8950982_-77.0363849_1994-07-04
Cache hit for 19.3207722_-99.1514678_1994-07-05
Cache hit for 9.0643305_7.4892974_1994-07-05
Cache hit for 41.8933203_12.4829321_1994-07-09
Cache hit for 52.3730796_4.8924534_1994-07-09
Cache hit for 42.6977028_23.3217359_1994-07-10
Cache hit for 44.4361414_26.102684_1994-07-10
Cache hit for 42.6977028_23.3217359_1994-07-13
Cache hit for 59.3251172_18.0710935_1994-07-13
Cache hit for 59.3251172_18.0710935_1994-07-16
Cache hit for -15.7939869_-47.8828_1994-07-17
Cache hit for -34.9058916_-56.1913095_1995-07-05
Cache hit for 19.3207722_-99.1514678_1995-07-06
Cache hit for -15.7939869_-47.8828_1995-07-07
Cache hit for 4.6533817_-74.0836331_1995-07-07
Cache hit for -34.6095579_-58.3887904_1995-07-08
Cache hit for 38.8950982_-77.0363849_1995-07-08
Cache hit for 19.3207722_-99.1514678_1995-07-09
Cache hit for -34.9058916_-56.1913095_1995-07-09
Cache hit for -15.7939869_-47.8828_1995-07-10
Cache hit for 4.6533817_-74.0836331_1995-07-10
Cache hit for -34.6095579_-58.3887904_1995-07-11
Cache hit for 38.8950982_-77.0363849_1995-07-11
Cache hit for -25.2800459_-57.6343814_1995-07-12
Cache hit for -15.7939869_-47.8828_1995-07-13
Cache hit for -12.0459808_-77.0305912_1995-07-13
Cache hit for -34.9058916_-56.1913095_1995-07-13
Cache hit for -34.6095579_-58.3887904_1995-07-14
Cache hit for -33.4376995_-70.6510671_1995-07-14
Cache hit for -25.2800459_-57.6343814_1995-07-16
Cache hit for -34.9058916_-56.1913095_1995-07-16
Cache hit for -15.7939869_-47.8828_1995-07-17
Cache hit for 38.8950982_-77.0363849_1995-07-17
Cache hit for -34.9058916_-56.1913095_1995-07-19
Cache hit for 38.8950982_-77.0363849_1995-07-20
Cache hit for 4.6533817_-74.0836331_1995-07-22
Cache hit for -34.9058916_-56.1913095_1995-07-23
Cache hit for -25.7459277_28.1879101_1996-01-13
Cache hit for 6.8200066_-5.2776034_1996-01-14
Cache hit for -15.4163395_28.2818414_1996-01-14
Cache hit for 30.0443879_31.2357257_1996-01-15
Cache hit for 8.479004_-13.26795_1996-01-15
Cache hit for 0.4086518_9.4418849_1996-01-16
Cache hit for 36.8002068_10.1857757_1996-01-16
Cache hit for 36.7729333_3.0588445_1996-01-18
Cache hit for 3.8689867_11.5213344_1996-01-18
Cache hit for -4.3196982_15.3424196_1996-01-19
Cache hit for 5.5571096_-0.2012376_1996-01-19
Cache hit for 12.3681873_-1.5270944_1996-01-20
Cache hit for -25.7459277_28.1879101_1996-01-20
Cache hit for -25.966213_32.56745_1996-01-21
Cache hit for -8.8272699_13.2439512_1996-01-24
Cache hit for 12.3681873_-1.5270944_1996-01-24
Cache hit for 8.479004_-13.26795_1996-01-24
Cache hit for -25.7459277_28.1879101_1996-01-24
Cache hit for 6.3203562_-10.8060492_1996-01-25
Cache hit for -25.966213_32.56745_1996-01-25
Cache hit for 36.8002068_10.1857757_1996-01-25
Cache hit for -25.7459277_28.1879101_1996-01-27
Cache hit for -15.4163395_28.2818414_1996-01-27
Cache hit for 0.4086518_9.4418849_1996-01-28
Cache hit for 5.5571096_-0.2012376_1996-01-28
Cache hit for -25.7459277_28.1879101_1996-01-31
Cache hit for -15.4163395_28.2818414_1996-01-31
Cache hit for -25.7459277_28.1879101_1996-02-03
Cache hit for -15.4163395_28.2818414_1996-02-03
Cache hit for 55.6867243_12.5700724_1996-06-09
Cache hit for 52.5173885_13.3951309_1996-06-09
Cache hit for 40.416782_-3.703507_1996-06-09
Cache hit for 52.3730796_4.8924534_1996-06-10
Cache hit for 44.4361414_26.102684_1996-06-10
Cache hit for 41.8933203_12.4829321_1996-06-11
Cache hit for 39.9207759_32.8540497_1996-06-11
Cache hit for 42.6977028_23.3217359_1996-06-13
Cache hit for 46.9484742_7.4521749_1996-06-13
Cache hit for 50.0874654_14.4212535_1996-06-14
Cache hit for 38.7077507_-9.1365919_1996-06-14
Cache hit for 48.8534951_2.3483915_1996-06-15
Cache hit for 45.8130967_15.9772795_1996-06-16
Cache hit for 55.625578_37.6063916_1996-06-16
Cache hit for 48.8534951_2.3483915_1996-06-18
Cache hit for 44.4361414_26.102684_1996-06-18
Cache hit for 55.9533456_-3.1883749_1996-06-18
Cache hit for 45.8130967_15.9772795_1996-06-19
Cache hit for 41.8933203_12.4829321_1996-06-19
Cache hit for 55.625578_37.6063916_1996-06-19
Cache hit for 39.9207759_32.8540497_1996-06-19
Cache hit for 48.8534951_2.3483915_1996-06-22
Cache hit for 50.0874654_14.4212535_1996-06-23
Cache hit for 52.5173885_13.3951309_1996-06-23
Cache hit for 48.8534951_2.3483915_1996-06-26
Cache hit for 50.0874654_14.4212535_1996-06-30
Cache hit for -6.1754049_106.827168_1996-12-04
Cache hit for 24.4538352_54.3774014_1996-12-04
Cache hit for 35.6892523_51.3896004_1996-12-05
Cache hit for 24.638916_46.7160104_1996-12-05
Cache hit for 39.9057136_116.3912972_1996-12-06
Cache hit for 35.6768601_139.7638947_1996-12-06
Cache hit for 37.5666791_126.9782914_1996-12-07
Cache hit for 24.4538352_54.3774014_1996-12-07
Cache hit for 24.638916_46.7160104_1996-12-08
Cache hit for 13.7524938_100.4935089_1996-12-08
Cache hit for 35.6768601_139.7638947_1996-12-09
Cache hit for 33.5130695_36.3095814_1996-12-09
Cache hit for 29.3796532_47.9734174_1996-12-10
Cache hit for 24.4538352_54.3774014_1996-12-10
Cache hit for 33.3061701_44.3872213_1996-12-11
Cache hit for 24.638916_46.7160104_1996-12-11
Cache hit for 35.6768601_139.7638947_1996-12-12
Cache hit for 41.3123363_69.2787079_1996-12-12
Cache hit for 29.3796532_47.9734174_1996-12-15
Cache hit for 24.4538352_54.3774014_1996-12-15
Cache hit for 37.5666791_126.9782914_1996-12-16
Cache hit for 24.638916_46.7160104_1996-12-16
Cache hit for 35.6892523_51.3896004_1996-12-19
Cache hit for 24.4538352_54.3774014_1996-12-19
Cache hit for 35.6892523_51.3896004_1996-12-21
Cache hit for 24.4538352_54.3774014_1996-12-21
Cache hit for -34.6095579_-58.3887904_1997-06-11
Cache hit for -33.4376995_-70.6510671_1997-06-11
Cache hit for -19.0477251_-65.2594306_1997-06-12
Cache hit for -12.0459808_-77.0305912_1997-06-12
Cache hit for -15.7939869_-47.8828_1997-06-13
Cache hit for 19.3207722_-99.1514678_1997-06-13
Cache hit for -34.6095579_-58.3887904_1997-06-14
Cache hit for -25.2800459_-57.6343814_1997-06-14
Cache hit for -19.0477251_-65.2594306_1997-06-15
Cache hit for -34.9058916_-56.1913095_1997-06-15
Cache hit for -15.7939869_-47.8828_1997-06-16
Cache hit for 4.6533817_-74.0836331_1997-06-16
Cache hit for -34.6095579_-58.3887904_1997-06-17
Cache hit for -33.4376995_-70.6510671_1997-06-17
Cache hit for -19.0477251_-65.2594306_1997-06-18
Cache hit for -12.0459808_-77.0305912_1997-06-18
Cache hit for -15.7939869_-47.8828_1997-06-19
Cache hit for 19.3207722_-99.1514678_1997-06-19
Cache hit for -19.0477251_-65.2594306_1997-06-21
Cache hit for -12.0459808_-77.0305912_1997-06-21
Cache hit for -15.7939869_-47.8828_1997-06-22
Cache hit for -0.2201641_-78.5123274_1997-06-22
Cache hit for -19.0477251_-65.2594306_1997-06-25
Cache hit for -15.7939869_-47.8828_1997-06-26
Cache hit for 19.3207722_-99.1514678_1997-06-28
Cache hit for -19.0477251_-65.2594306_1997-06-29
Cache hit for 12.3681873_-1.5270944_1998-02-07
Cache hit for 36.7729333_3.0588445_1998-02-08
Cache hit for 6.8200066_-5.2776034_1998-02-08
Cache hit for -25.7459277_28.1879101_1998-02-08
Cache hit for -4.3196982_15.3424196_1998-02-09
Cache hit for 5.5571096_-0.2012376_1998-02-09
Cache hit for -15.4163395_28.2818414_1998-02-09
Cache hit for 30.0443879_31.2357257_1998-02-10
Cache hit for 12.3681873_-1.5270944_1998-02-11
Cache hit for 3.8689867_11.5213344_1998-02-11
Cache hit for -25.7459277_28.1879101_1998-02-11
Cache hit for -8.8272699_13.2439512_1998-02-12
Cache hit for 5.5571096_-0.2012376_1998-02-12
Cache hit for 36.8002068_10.1857757_1998-02-12
Cache hit for 34.0218454_-6.8408929_1998-02-13
Cache hit for -15.4163395_28.2818414_1998-02-13
Cache hit for 12.3681873_-1.5270944_1998-02-15
Cache hit for 3.8689867_11.5213344_1998-02-15
Cache hit for 5.5571096_-0.2012376_1998-02-16
Cache hit for 6.8200066_-5.2776034_1998-02-16
Cache hit for -25.7459277_28.1879101_1998-02-16
Cache hit for 36.8002068_10.1857757_1998-02-16
Cache hit for 30.0443879_31.2357257_1998-02-17
Cache hit for -15.4163395_28.2818414_1998-02-17
Cache hit for 3.8689867_11.5213344_1998-02-20
Cache hit for 12.3681873_-1.5270944_1998-02-21
Cache hit for 6.8200066_-5.2776034_1998-02-21
Cache hit for 34.0218454_-6.8408929_1998-02-22
Cache hit for 12.3681873_-1.5270944_1998-02-25
Cache hit for -4.3196982_15.3424196_1998-02-25
Cache hit for 12.3681873_-1.5270944_1998-02-27
Cache hit for -25.7459277_28.1879101_1998-02-28
Cache hit for -15.7939869_-47.8828_1998-06-10
Cache hit for 34.0218454_-6.8408929_1998-06-10
Cache hit for 3.8689867_11.5213344_1998-06-11
Cache hit for 41.8933203_12.4829321_1998-06-11
Cache hit for 48.8534951_2.3483915_1998-06-12
Cache hit for -25.2800459_-57.6343814_1998-06-12
Cache hit for 24.638916_46.7160104_1998-06-12
Cache hit for 37.5666791_126.9782914_1998-06-13
Cache hit for 52.3730796_4.8924534_1998-06-13
Cache hit for 40.416782_-3.703507_1998-06-13
Cache hit for -34.6095579_-58.3887904_1998-06-14
Cache hit for 17.9712148_-76.7928128_1998-06-14
Cache hit for 44.8153318_20.4456588_1998-06-14
Cache hit for 52.5173885_13.3951309_1998-06-15
Cache hit for 44.4361414_26.102684_1998-06-15
Cache hit for -15.7939869_-47.8828_1998-06-16
Cache hit for 55.9533456_-3.1883749_1998-06-16
Cache hit for -33.4376995_-70.6510671_1998-06-17
Cache hit for 41.8933203_12.4829321_1998-06-17
Cache hit for 48.8534951_2.3483915_1998-06-18
Cache hit for -25.7459277_28.1879101_1998-06-18
Cache hit for 9.0643305_7.4892974_1998-06-19
Cache hit for 40.416782_-3.703507_1998-06-19
Cache hit for 50.8467372_4.352493_1998-06-20
Cache hit for 35.6768601_139.7638947_1998-06-20
Cache hit for 52.3730796_4.8924534_1998-06-20
Cache hit for -34.6095579_-58.3887904_1998-06-21
Cache hit for 52.5173885_13.3951309_1998-06-21
Cache hit for 38.8950982_-77.0363849_1998-06-21
Cache hit for 4.6533817_-74.0836331_1998-06-22
Cache hit for -15.7939869_-47.8828_1998-06-23
Cache hit for -33.4376995_-70.6510671_1998-06-23
Cache hit for 41.8933203_12.4829321_1998-06-23
Cache hit for 55.9533456_-3.1883749_1998-06-23
Cache hit for 48.8534951_2.3483915_1998-06-24
Cache hit for 9.0643305_7.4892974_1998-06-24
Cache hit for -25.7459277_28.1879101_1998-06-24
Cache hit for 40.416782_-3.703507_1998-06-24
Cache hit for 50.8467372_4.352493_1998-06-25
Cache hit for 52.5173885_13.3951309_1998-06-25
Cache hit for 52.3730796_4.8924534_1998-06-25
Cache hit for 38.8950982_-77.0363849_1998-06-25
Cache hit for -34.6095579_-58.3887904_1998-06-26
Cache hit for 35.6768601_139.7638947_1998-06-26
Cache hit for 44.4361414_26.102684_1998-06-26
Cache hit for -15.7939869_-47.8828_1998-06-27
Cache hit for 41.8933203_12.4829321_1998-06-27
Cache hit for 48.8534951_2.3483915_1998-06-28
Cache hit for 9.0643305_7.4892974_1998-06-28
Cache hit for 52.5173885_13.3951309_1998-06-29
Cache hit for 52.3730796_4.8924534_1998-06-29
Cache hit for 44.4361414_26.102684_1998-06-30
Cache hit for -15.7939869_-47.8828_1998-07-03
Cache hit for 48.8534951_2.3483915_1998-07-03
Cache hit for 52.5173885_13.3951309_1998-07-04
Cache hit for 52.3730796_4.8924534_1998-07-04
Cache hit for -15.7939869_-47.8828_1998-07-07
Cache hit for 48.8534951_2.3483915_1998-07-08
Cache hit for 52.3730796_4.8924534_1998-07-11
Cache hit for 48.8534951_2.3483915_1998-07-12
Cache hit for -25.2800459_-57.6343814_1999-06-29
Cache hit for -12.0459808_-77.0305912_1999-06-29
Cache hit for -15.7939869_-47.8828_1999-06-30
Cache hit for -33.4376995_-70.6510671_1999-06-30
Cache hit for -34.6095579_-58.3887904_1999-07-01
Cache hit for -34.9058916_-56.1913095_1999-07-01
Cache hit for -25.2800459_-57.6343814_1999-07-02
Cache hit for -12.0459808_-77.0305912_1999-07-02
Cache hit for -15.7939869_-47.8828_1999-07-03
Cache hit for -33.4376995_-70.6510671_1999-07-03
Cache hit for -34.6095579_-58.3887904_1999-07-04
Cache hit for -34.9058916_-56.1913095_1999-07-04
Cache hit for -19.0477251_-65.2594306_1999-07-05
Cache hit for -25.2800459_-57.6343814_1999-07-05
Cache hit for -15.7939869_-47.8828_1999-07-06
Cache hit for 19.3207722_-99.1514678_1999-07-06
Cache hit for 4.6533817_-74.0836331_1999-07-07
Cache hit for -34.9058916_-56.1913095_1999-07-07
Cache hit for 19.3207722_-99.1514678_1999-07-10
Cache hit for -25.2800459_-57.6343814_1999-07-10
Cache hit for -15.7939869_-47.8828_1999-07-11
Cache hit for -33.4376995_-70.6510671_1999-07-11
Cache hit for -34.9058916_-56.1913095_1999-07-13
Cache hit for 19.3207722_-99.1514678_1999-07-14
Cache hit for -33.4376995_-70.6510671_1999-07-17
Cache hit for -15.7939869_-47.8828_1999-07-18
Cache hit for 5.5571096_-0.2012376_2000-01-22
Cache hit for 30.0443879_31.2357257_2000-01-23
Cache hit for 9.0643305_7.4892974_2000-01-23
Cache hit for -25.7459277_28.1879101_2000-01-23
Cache hit for -4.3196982_15.3424196_2000-01-24
Cache hit for 6.8200066_-5.2776034_2000-01-24
Cache hit for 12.3681873_-1.5270944_2000-01-25
Cache hit for 34.0218454_-6.8408929_2000-01-25
Cache hit for 5.5571096_-0.2012376_2000-01-27
Cache hit for -25.7459277_28.1879101_2000-01-27
Cache hit for 3.8689867_11.5213344_2000-01-28
Cache hit for 30.0443879_31.2357257_2000-01-28
Cache hit for 9.0643305_7.4892974_2000-01-28
Cache hit for 36.7729333_3.0588445_2000-01-29
Cache hit for 36.8002068_10.1857757_2000-01-29
Cache hit for -15.4163395_28.2818414_2000-01-29
Cache hit for 3.8689867_11.5213344_2000-01-31
Cache hit for 5.5571096_-0.2012376_2000-01-31
Cache hit for 30.0443879_31.2357257_2000-02-01
Cache hit for -15.4163395_28.2818414_2000-02-01
Cache hit for -4.3196982_15.3424196_2000-02-02
Cache hit for -25.7459277_28.1879101_2000-02-02
Cache hit for 9.0643305_7.4892974_2000-02-03
Cache hit for 36.8002068_10.1857757_2000-02-03
Cache hit for 3.8689867_11.5213344_2000-02-06
Cache hit for 5.5571096_-0.2012376_2000-02-06
Cache hit for 30.0443879_31.2357257_2000-02-07
Cache hit for 9.0643305_7.4892974_2000-02-07
Cache hit for 3.8689867_11.5213344_2000-02-10
Cache hit for 9.0643305_7.4892974_2000-02-10
Cache hit for -25.7459277_28.1879101_2000-02-12
Cache hit for 9.0643305_7.4892974_2000-02-13
Cache hit for 50.8467372_4.352493_2000-06-10
Cache hit for 48.8534951_2.3483915_2000-06-11
Cache hit for 52.3730796_4.8924534_2000-06-11
Cache hit for 39.9207759_32.8540497_2000-06-11
Cache hit for 52.5173885_13.3951309_2000-06-12
Cache hit for 44.8153318_20.4456588_2000-06-13
Cache hit for 40.416782_-3.703507_2000-06-13
Cache hit for 50.8467372_4.352493_2000-06-14
Cache hit for 59.3251172_18.0710935_2000-06-15
Cache hit for 50.0874654_14.4212535_2000-06-16
Cache hit for 52.3730796_4.8924534_2000-06-16
Cache hit for 44.4361414_26.102684_2000-06-17
Cache hit for 59.9133301_10.7389701_2000-06-18
Cache hit for 46.0500268_14.5069289_2000-06-18
Cache hit for 50.8467372_4.352493_2000-06-19
Cache hit for 41.8933203_12.4829321_2000-06-19
Cache hit for 38.7077507_-9.1365919_2000-06-20
Cache hit for 55.6867243_12.5700724_2000-06-21
Cache hit for 52.3730796_4.8924534_2000-06-21
Cache hit for 44.8153318_20.4456588_2000-06-21
Cache hit for 46.0500268_14.5069289_2000-06-21
Cache hit for 41.8933203_12.4829321_2000-06-24
Cache hit for 39.9207759_32.8540497_2000-06-24
Cache hit for 52.3730796_4.8924534_2000-06-25
Cache hit for 40.416782_-3.703507_2000-06-25
Cache hit for 48.8534951_2.3483915_2000-06-28
Cache hit for 52.3730796_4.8924534_2000-06-29
Cache hit for 48.8534951_2.3483915_2000-07-02
Cache hit for 33.3061701_44.3872213_2000-10-12
Cache hit for 33.8892265_35.5025585_2000-10-12
Cache hit for 37.5666791_126.9782914_2000-10-13
Cache hit for 29.3796532_47.9734174_2000-10-13
Cache hit for 25.3108807_51.5081812_2000-10-14
Cache hit for 24.638916_46.7160104_2000-10-14
Cache hit for 35.6892523_51.3896004_2000-10-15
Cache hit for 33.8892265_35.5025585_2000-10-15
Cache hit for 39.9057136_116.3912972_2000-10-16
Cache hit for 37.5666791_126.9782914_2000-10-16
Cache hit for 35.6768601_139.7638947_2000-10-17
Cache hit for 24.638916_46.7160104_2000-10-17
Cache hit for 35.6892523_51.3896004_2000-10-18
Cache hit for 33.8892265_35.5025585_2000-10-18
Cache hit for 39.9057136_116.3912972_2000-10-19
Cache hit for 37.5666791_126.9782914_2000-10-19

In [ ]:

unique = train[['away_lat', 'away_lon', 'date']].drop_duplicates()

unique['weather'] = unique.apply(
    lambda row: get_weather(row['away_lat'], row['away_lon'], row['date']),
    axis=1
)

weather_df = unique['weather'].apply(pd.Series)
unique = pd.concat([unique, weather_df], axis=1).drop(columns='weather')

train = train.merge(unique, on=['away_lat', 'away_lon', 'date'], how='left')

In [ ]:

unique = train[['stadium_lat', 'stadium_lon', 'date']].drop_duplicates()

unique['weather'] = unique.apply(
    lambda row: get_weather(row['stadium_lat'], row['stadium_lon'], row['date']),
    axis=1
)

weather_df = unique['weather'].apply(pd.Series)
unique = pd.concat([unique, weather_df], axis=1).drop(columns='weather')

train = train.merge(unique, on=['stadium_lat', 'stadium_lon', 'date'], how='left')